#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mythes
Version  : 2e09086d89ce8e7e73376b92cf67c1798fc47b5f
Release  : 1
URL      : https://github.com/hunspell/mythes/archive/2e09086d89ce8e7e73376b92cf67c1798fc47b5f.tar.gz
Source0  : https://github.com/hunspell/mythes/archive/2e09086d89ce8e7e73376b92cf67c1798fc47b5f.tar.gz
Summary  : MyThes spellchecking library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mythes-bin
Requires: mythes-lib
Requires: mythes-license
BuildRequires : pkgconfig(hunspell)

%description
MyThes is a simple thesaurus that uses a structured
text data file and an index file with binary search
to lookup words and phrases and return information
on part of speech, meanings, and synonyms

%package bin
Summary: bin components for the mythes package.
Group: Binaries
Requires: mythes-license

%description bin
bin components for the mythes package.


%package dev
Summary: dev components for the mythes package.
Group: Development
Requires: mythes-lib
Requires: mythes-bin
Provides: mythes-devel

%description dev
dev components for the mythes package.


%package lib
Summary: lib components for the mythes package.
Group: Libraries
Requires: mythes-license

%description lib
lib components for the mythes package.


%package license
Summary: license components for the mythes package.
Group: Default

%description license
license components for the mythes package.


%prep
%setup -q -n mythes-2e09086d89ce8e7e73376b92cf67c1798fc47b5f

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533756858
%autogen --disable-static --disable-werror
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533756858
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mythes
cp COPYING %{buildroot}/usr/share/doc/mythes/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/th_gen_idx.pl

%files dev
%defattr(-,root,root,-)
/usr/include/*.hxx
/usr/lib64/libmythes-1.2.so
/usr/lib64/pkgconfig/mythes.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmythes-1.2.so.0
/usr/lib64/libmythes-1.2.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/mythes/COPYING
